# Computing $h_\theta(x)$ for a  list of House sizes

## Matrix Vector Multiplication

source = https://www.coursera.org/learn/machine-learning/lecture/aQDta/matrix-vector-multiplication

Let us have a serie of house's sizes  

2104  
1416  
1534  
852

And a Hypothesis function $h_\theta(x) = -40  +0.25x$

**To Do:**  $h_\theta(x)$ for each size using matrices 

In [1]:
import numpy as np

In [3]:
X = np.array([[1,2104],[1,1416],[1,1534],[1,852]])

**Feature Matrix**

In [4]:
X

array([[   1, 2104],
       [   1, 1416],
       [   1, 1534],
       [   1,  852]])

**Theta Vector**

In [12]:
H = np.array([[-40],[0.25]])

In [13]:
H

array([[-40.  ],
       [  0.25]])

**Multiply the Feature Matrix by the Hypothesis Vector**

$h_\theta(x) =  \theta^T X$

In [14]:
np.dot(M,H)

array([[486. ],
       [314. ],
       [343.5],
       [173. ]])

Predicted prices of the 4 houses

## $Rule : $  
  
    
    

$ \space \space Prediction = Data Matrix \space \space X  \space \space Parameters$