In [1]:
import numpy as np

np.dot(a,b) : returns the dot product (scalar product) of vectors **a** and **b**.  
Can perform matrix multiplication.

### Product of scalar values

In [2]:
np.dot(5,3)

15

### Matrices with Numpy

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A)
print(B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


### Scalar X Vector

In [10]:
v = np.array([[5,9]])
5*v

array([[25, 45]])

### Multiplication of 2 Matrices with numpy

In [7]:
A.dot(B)

array([[19, 22],
       [43, 50]])

In [16]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

### Transpose of a matrix

In [14]:
M = np.array([[1,2,3,4,5]])
M

array([[1, 2, 3, 4, 5]])

In [15]:
M.transpose()

array([[1],
       [2],
       [3],
       [4],
       [5]])