In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[11,22,33]])
b = np.array([[4,5,6],[44,55,66]])

In [6]:
a

array([[ 1,  2,  3],
       [11, 22, 33]])

In [7]:
b

array([[ 4,  5,  6],
       [44, 55, 66]])

### np.r_(x,y) : Concatenates along the rows

In [8]:
np.r_[a,b]

array([[ 1,  2,  3],
       [11, 22, 33],
       [ 4,  5,  6],
       [44, 55, 66]])

### np.c_(x,y) : Concatenates along the columns

In [9]:
np.c_[a,b]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])